services:
  db:
    image: pgvector/pgvector:pg16
    container_name: lenny_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: lenny_assistant
    ports:
       - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lenny_assistant"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: